import 'package:flutter/material.dart';

class CategoryIcons {
  static const Map<String, IconData> expense = {
    'Shopping': Icons.shopping_cart_outlined,
    'Food': Icons.restaurant_outlined,
    'Phone': Icons.smartphone_outlined,
    'Entertainment': Icons.sports_esports_outlined,
    'Education': Icons.school_outlined,
    'Beauty': Icons.content_cut_outlined,
    'Sports': Icons.directions_run_outlined,
    'Social': Icons.people_outline,
    'Transportation': Icons.directions_bus_outlined,
    'Clothing': Icons.checkroom_outlined,
    'Car': Icons.directions_car_outlined,
    'Alcohol': Icons.wine_bar_outlined,
    'Cigarettes': Icons.smoking_rooms_outlined,
    'Electronics': Icons.computer_outlined,
    'Travel': Icons.flight_outlined,
    'Health': Icons.monitor_heart_outlined,
    'Pets': Icons.pets_outlined,
    'Repairs': Icons.build_outlined,
    'Housing': Icons.home_outlined,
    'Home': Icons.weekend_outlined,
    'Gifts': Icons.card_giftcard_outlined,
    'Donations': Icons.volunteer_activism_outlined,
    'Lottery': Icons.casino_outlined,
    'Snacks': Icons.takeout_dining_outlined,
    'Love': Icons.favorite_border,
    'Trips': Icons.toys_rounded,
    'Other': Icons.more_horiz,
  };

  static const Map<String, IconData> income = {
    'Salary': Icons.account_balance_wallet_outlined,
    'Business': Icons.business_center_outlined,
    'Freelance': Icons.laptop_mac_outlined,
    'Investment': Icons.trending_up_outlined,
    'Interest': Icons.savings_outlined,
    'Bonus': Icons.workspace_premium_outlined,
    'Commission': Icons.payments_outlined,
    'Rental Income': Icons.home_work_outlined,
    'Cashback': Icons.redeem_outlined,
    'Refund': Icons.assignment_return_outlined,
    'Gift': Icons.card_giftcard_outlined,
    'Lottery': Icons.casino_outlined,
    'Scholarship': Icons.school_outlined,
    'Pension': Icons.elderly_outlined,
    'Government Benefit': Icons.account_balance_outlined,
    'Insurance Claim': Icons.health_and_safety_outlined,
    'Dividends': Icons.show_chart_outlined,
    'Savings Withdrawal': Icons.account_balance_wallet,
    'Family Support': Icons.favorite_border,
    'Selling Items': Icons.sell_outlined,
    'Online Earnings': Icons.public_outlined,
    'Reward': Icons.emoji_events_outlined,
    'Profit': Icons.monetization_on_outlined,
    'Side Hustle': Icons.work_outline,
    'Other': Icons.more_horiz,
  };
}
